{% set version = "1.0.2" %}

package:
  name: wrf-python
  version: {{ version }}

source:
  fn: wrf-python-{{ version }}.tar.gz
  url: https://github.com/NCAR/wrf-python/archive/{{ version }}.tar.gz
  sha256: 42df1c46c146010e8d7a14cfa4daca3c30cb530e93d26e1fba34e2118540e0b2

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: True  # [(win and py>=35)]

requirements:
  build:
    - setuptools
    - numpy x.x
    - wrapt
    - mingwpy  # [win]
    - gcc  # [unix]
    - python
  run:
    - numpy x.x
    - python
    - wrapt 
    - mingwpy  # [win]
    - libgfortran  # [unix]
    - libgcc  # [unix]
    - xarray

test:
  requires:
    - netcdf4
    - xarray
  source_files:
    - test/ci_tests
  imports:
    - wrf
  commands:
    - cd test/ci_tests && python utests.py 

about:
  home: https://github.com/NCAR/wrf-python
  license: "UCAR"
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE' 
  summary: "Diagnostic and interpolation routines for WRF-ARW data."

extra:
  recipe-maintainers:
    - bladwig1
    - marylhaley
    - david-ian-brown
    - khallock
